all:
	rm -r build
	cp -r ../doc build
	rm -r build/matrix
	rm -r build/search.d
	rm build/doc_backlink_crossref.html
	rm build/doc_keyword_crossref.html
	rm build/doc_pagelink_crossref.html
	rm build/doc_target_crossref.html
